### ISSUE TITLE
Implement Tweet Collector Class Infrastructure

### ISSUE THREAD

**Issue by dickensc** [ThePolarizationOfInformationOnTheWeb/ThePolarizationOfInformation#14]
Implement the TweetCollector class infrastructure. Use Tweepy and Twitter API
Read keys from a file we will save on our own machines. 

init(): Set up connection with API and open file for writing
- [x] args: _topic_: The topic the instance is concerned with
- [x] optional args: _path_to_keys_: Assume path and name of file for keys as default.
                 the default will be ./keys.csv and keys.csv will be a csv file with 1 row no index and a header labeling the index columns "consumer_key", "consumer_secret", "access_token", "access_token_secret".
- [x] open \<topic\>_tweets.csv file and make list of existing tweets.

Methods:
- [x] _collect_tweets()_: Method to make queries for tweets on a topic. 
> - [x] args: _queries_: search to make.
> - [x] optional args: options matching the search method for Tweepy
> - [x] Must conform to API limits ( ex. do not exceed access limits and if you are, wait ). (tweepy implements this for us)
> - [x] Tweet Feature Extraction: since we are limited by the number of tweets we can collect per month we need to collect all info at once, => store entire .json format of tweet into \<Topic\>_Tweet.csv 
> - [x] At the end of the method: we create new \<Topic\>_Tweets.csv file of results or append to existing file.
> - If file already exists ensure that you do not store duplicates! (an efficient solution may be to read in existing data at init, and the unique tweet_ID of the new entry should be a easy mapping)

**Comment by dickensc** [comment]
Start with this and we will add a new methods to collect other features from the Tweets such as the 20 most recent likes among those who liked the tweet, # retweets, and so forth.

**Comment by prajjwaldangal** [comment]
I told you about the beanstalk and twitter-python project. That looks complicated and not well documented. So if you find some starter code, do share it with me. Thanks

**Comment by dickensc** [comment]
I started for this issue you can start on and I use tweepy, but we are kind of at a wall until we get the access tokens
